language: node_js
node_js: '12'
dist: bionic
# When pushing a tagged commit, Travis adds two builds: one with the tag, one
# without. We only want to build the one with the tag, because it's the one
# that runs the deployment stage
if: '!(commit_message =~ /^Release/ && tag is blank)'
jobs:
  include:
    # Test on Windows/Mac/Linux using latest Node.js.
    # Also test on Linux with older Node.js versions.
    # We do not run each possible combination to make CI faster.
    - os: windows
    - os: osx
    - node_js: '8.12.0'
    - node_js: '12'
    # Deployment must happen after tests for the whole matrix have been
    # performed, so we use `jobs.include` with a different `stage`.
    - stage: Deploy
      if: type != pull_request && tag is not blank
      script: gulp publish
      # NPM_TOKEN environment variable
      env:
        secure: 'ZSuOAK74iJwefrNpRMCaQ3fUz8Y5Wh+beCXSWrZGY+u1scEvDmMiPRcbqS0Mvzy36O3SAtPDMG2M+BpBBSjsPBKksXdb643TN2eOxpsYzYp32VFN+KFkb7lFjffVShPkHrrKO96pa0mp2cj2AYjvtMaME5zmbJZVFWbDcWn5BQiaBJ+LrBTsnquRVntGMUbVwO6O5jm7cYX9P8LK1qiHLlLwkkTynarcqTIjB0Qao/RFdwTqpPmEM5lxySX4MT8MRAEjdyYApJYZ/uSHb6OwMAJhcWCgRahvvxodiiW0xActmVpPB+MIkeq0vRHlG2hBgeqSudhMMJC0Ugj/PecLsDAHVYY3b3Kfk1jWQLGJaJkRQFdkbMKeLqUghc1aYS6/sqT1rn+Y2cApGMTUhAeuSbb0R+mb2l7gqEMTFZ00qlLxCwo0S00XVUgJoKOO7xkEDNlldIYMeIVpXk79MEdlFTA32R/7kUiyp3BKdj0wxFj1jsJFxZzuBUq2RSegeCZ7aAg53lvcylrefiHZWPAkjYNLjGyao1Rb+lNCixgnV0uF2674enAhIDFaldY/8Ddo1d55KPIcnyXIxfrbc0bhbg/OuuZA/l8sez/2J0qV1l0+XJPbHb136AJrQ20Ud3fgXTrnW48g+/o7jFMQwwzh2AUYnFJnPAy5HSchHvq6BXg='
notifications:
  webhooks:
    - https://www.travisbuddy.com?only=failed,errored&insertMode=update
  email: false
# We do not use `cache: npm` because downloading and uploading the cache
# actually takes more time than it saves during `npm ci`.
